version: '3.4'

services:
  postgres:
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  pollssystem.api:
    container_name: polls-system-api
    restart: unless-stopped
    ports:
      - "6000:80"

volumes:
  postgres:
    driver: local
