version: '3.4'

services:
  postgres:
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  proxy:
    container_name: polls-system-proxy
    restart: unless-stopped
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      #- "443:443"

  #certbot:
  #  container_name: certbot
  #  restart: unless-stopped
  #  depends_on:
  #    - proxy
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot
  #  command: certonly --webroot --webroot-path=/var/www/certbot --force-renewal --email tkachuko_09@knu.ua --agree-tos --no-eff-email -d polls-system.com -d www.polls-system.com

  polls-system-api:
    container_name: polls-system-api
    ports:
      - "5000:80"

  polls-system-client:
    container_name: polls-system-client
    ports:
      - "4200:4200"
