version: "3.7"

services:
  polls-system-api:
    build:
      context: ../
      dockerfile: backend/src/PollsSystem.Api/Dockerfile
    container_name: polls-system-api
    restart: unless-stopped
    ports: 
      - 5000:80
    networks:
      - polls-system

  polls-system-client:
    build: 
      context: ../
      dockerfile: client/Dockerfile
    container_name: polls-system-client
    restart: unless-stopped
    ports: 
      - 4200:4200
    networks:
      - polls-system

  proxy:
    image: nginx:latest
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

networks:
  polls-system:
    name: polls-system
    external: true